### PR TITLE
RHOAIENG-9803-Create a sample Git fetch pipeline in manifests

### PR DESCRIPTION
**Pull request by biswassri**
## Description

A pipeline that does the same as the MLops pipeline but now with just the git fetch task as the fetch method. This change also removes the aiedge-e2e-pipeline from the kustomization file. So the files remains but the pipeline is not gonna get created.

## How Has This Been Tested?

Tested the changes using the below commands
```
oc apply -k manifests/
oc create -f pipelines/tekton/aiedge-e2e/git-fetch-tensorflow-housing.pipelinerun.yaml
```
Screenshot 2024-07-29 at 6 15 11 PM

## Merge criteria:

- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Comment by jackdelahunt** [comment]
Prow will fail because the `pipelines-test-openvino-tensorflow-housing.sh` needs to be updated to use the new pipeline run. I don't think there should be any other breaking changes for that.

E2e-tests will also need to be updated

**Comment by biswassri** [comment]
Thanks @jackdelahunt. I was just going through them. I referred to your PR for the change points. 👍🏻

**Comment by biswassri** [comment]
Closing out this PR, I did some naming changing incorrectly and the gitlog is getting super complex to resolve. Will replace this with a new PR and same changes.

**Pull request closed without merging**
