### PR TITLE
RHOAIENG-3458: Add a models command to the CLI

### PR DESCRIPTION
**Pull request by devguyio**
## Description

Add a `models` command that lists registered models from the model registry. 

This PR is stacked on top of #222 .

## How Has This Been Tested?

- Install models registry in your kubecluster following [this video ](https://www.youtube.com/watch?v=grXnjGtDFXg)
- Port-forward port 8080 of the `modelregistry-sample` service in the namespace where you installed the model registry
```shell
kubectl port-forward services/modelregistry-sample 8080
```
- From the `cli` directory, run the cli using go, the URL of the model registry is set via the env var `MODEL_REGISTRY_URL` which defaults to `http://localhost:8080` .
```shell
cd cli
go run cmd/main.go
```
image

## Merge criteria:

- [ ] The commits are squashed in a cohesive manner and have meaningful messages.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Review by MarianMacik — COMMENTED** [review]
Looks good, I have just one question about the currently unused fields of the model.

**Review by grdryn — COMMENTED** [review]
Feel free to disregard my Go-related comments, since I haven't used it in about 3 years probably, and have never used the bubbletea stuff :upside_down_face:

**Comment by devguyio** [comment]
@grdryn thanks for the review. This PR was merged by mistake and a lot of the comments you mentioned were addressed in #234 . Basically, the `models` command was refactored in #234 to use the edge client and also be ready for merge. 

So I suggest that you check that PR and consider it the proposed state of the `models` command? wdyt?

**Comment by grdryn** [comment]
Yeah, for sure, I plan to get around to looking at #234 soon too. I just figured that one would make more sense once I'd seen these earlier ones (that I know you'd mentioned had been merged accidentally).

**Pull request merged**
