### PR TITLE
Delete unused parameters from pipeline and tasks

### PR DESCRIPTION
**Pull request by MarianMacik**
## Description
This removes 2 unused parameters:
* `current-namespace` from `check-model-and-containerfile-exists` and `kserve-download-model` tasks
* `model-name` from `gitops-update-pipeline`

## How Has This Been Tested?
PR check

## Merge criteria:

- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Review by jackdelahunt — COMMENTED** [review]
Removing these params looks fine. `model-name` should also be removed from the pipeline run example though

**Review by jackdelahunt — APPROVED** [review]

**Comment by MarianMacik** [comment]
> Removing these params looks fine. `model-name` should also be removed from the pipeline run example though for gitops

Good catch!
I also realized that I need to remove `current-namespace` from the ai-edge-e2e and s3-fetch pipelines. It is interesting that Tekton doesn't complain about passing superfluous parameters to tasks and pipelines.

**Review by biswassri — APPROVED** [review]
/lgtm

Looks good.

**Pull request merged**
