### PR TITLE
Increase timout for waiting for deployment and pods

### PR DESCRIPTION
**Pull request by MarianMacik**
## Description
Waiting for the Deployment is sometimes timing out even though there is no error, so it is just slower.

## How Has This Been Tested?
Local cluster (where the current timeout was enough), PR check will also test it on OpenShift CI infrastructure.

## Merge criteria:

- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Review by MarianMacik — COMMENTED** [review]
/approve

**Review by biswassri — APPROVED** [review]
/lgtm

**Pull request merged**
