### PR TITLE
Decouple GitOps Update pipeline from aiedge-e2e

### PR DESCRIPTION
**Pull request by grdryn**
JIRA: https://issues.redhat.com/browse/RHOAIENG-4982

## Description

Before this change, at least one PipelineRun for the specified model name from the aiedge-e2e Pipeline needed to exist on the cluster, to be able to successfully run the GitOps Update Pipeline.

This change instead accepts the image details explicitly as parameters in the GitOps Update Pipeline, making it more robust and applicable to more scenarios.

## How Has This Been Tested?

- [x] Tested that all of the updated pipelinerun examples work as expected.
- [x] Observed that the e2e test passes on this PR.

## Merge criteria:

- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Review by MarianMacik — COMMENTED** [review]
Looks good. I have just opened grdryn/ai-edge#36 to fix the tests. The explanation why the tests didn't fail here is in that PR. Now it should be OK and the tests would catch it. After that PR is merged, we can merge this too.

**Review by MarianMacik — APPROVED** [review]
/lgtm

**Comment by LaVLaS** [comment]
/approved

This worked for me without issues and no requirement for a pre-existing successful pipelinerun

**Review by LaVLaS — APPROVED** [review]
/approve

**Pull request merged**
