### PR TITLE
Increase timeout for the s3-fetch pipeline with bike-rentals

### PR DESCRIPTION
**Pull request by MarianMacik**
## Description
Just a timeout increase as pipeline is completing in 217-220 retries, sometimes failing because of not enough waiting time.

## How Has This Been Tested?
Periodic job.

## Merge criteria:

- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Review by biswassri — APPROVED** [review]

**Review by MarianMacik — COMMENTED** [review]
/approve

**Pull request merged**
