### PR TITLE
Use digests of newest images in quay.io/rhoai-edge/ repositories.

### PR DESCRIPTION
**Pull request by adelton**
## Description

Use digests of newest images in https://quay.io/organization/rhoai-edge repositories.

## How Has This Been Tested?

Not tested, just copied the SHA-256's from quay WebUI.

## Merge criteria:

- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Comment by piotrpdev** [comment]
Wouldn't using the older `1-2` versions of the images be better so we can showcase updating the digests to `1-3`? This would also be useful for testing/showcasing the PR feature without uploading a new image.

**Comment by adelton** [comment]
That makes sense. So the goal would be not to go with the newest but with the oldest?

On the other hand, you can still show how a different image gets used but going from the latest to `1-3` and to `1-2` ... so we don't lose much by going with the latest, plus things are easier to check for consistency.

**Comment by adelton** [comment]
Rebased on main.

**Review by piotrpdev — APPROVED** [review]
> going from the latest to 1-3 and to 1-2

That's actually a more realistic scenario, fair enough 😅

**Comment by adelton** [comment]
Thanks, merging.

**Pull request merged**
