### PR TITLE
Use the UBI image from the unauthenticated registry.

### PR DESCRIPTION
**Pull request by adelton**
## Description

Use the UBI image from the unauthenticated registry.

## How Has This Been Tested?

```bash
oc apply -f tekton/test-mlflow-image-pipeline/test-mlflow-rest-svc-task.yaml
oc create -f tekton/test-mlflow-image-pipeline/test-mlflow-image-pipelinerun-tensorflow-housing.yaml
```

## Merge criteria:

- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Review by piotrpdev — APPROVED** [review]

**Comment by piotrpdev** [comment]
Do you want to switch it to the minimal image? That should probably still work.

**Comment by adelton** [comment]
> Do you want to switch it to the minimal image? That should probably still work.

That does not seem to contain `curl`.

**Comment by piotrpdev** [comment]
> > Do you want to switch it to the minimal image? That should probably still work.
> 
> That does not seem to contain `curl`.

image

**Comment by adelton** [comment]
You are right about `-minimal` -- I had `ubi-micro` in mind.

**Pull request merged**
