### PR TITLE
Remove unnecessary line in a code block in e2e tests README

### PR DESCRIPTION
**Pull request by jackdelahunt**
## Description
Removes a line that was pasted by mistake in a code block in the e2e tests README.

- [x] The commits are squashed in a cohesive manner and have meaningful messages.

### CODE REVIEW

**Review by grdryn — APPROVED** [review]
/lgtm

**Review by MarianMacik — APPROVED** [review]

**Comment by grdryn** [comment]
@MarianMacik can you add the approve comment so that this will get merged?

**Comment by MarianMacik** [comment]
> @MarianMacik can you add the approve comment so that this will get merged?

Sorry, I was already away.

**Pull request merged**
