### PR TITLE
Clarify edge UWM info in the README

### PR DESCRIPTION
**Pull request by LaVLaS**
## Description
Update the  existing Observability setup instructions to add some minor context to the steps for enabling UserWorkloadMonitoring.

## How Has This Been Tested?
Deployed manually to a new cluster

## Merge criteria:
No errors introduced

- [ ] The commits are squashed in a cohesive manner and have meaningful messages.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Comment by adelton** [comment]
If amending / fixing the `Makefile`, please also document what it is for, where it is used. See also https://github.com/opendatahub-io/ai-edge/issues/110.

**Review by grdryn — APPROVED** [review]
LGTM.

@adelton's comment about the Make targets not being mentioned in the instructions is a good point too though. Given that he has created #110 for that, I don't have strong feelings either way about whether that should be addressed here or in a follow-up PR for that issue.

**Review by piotrpdev — APPROVED** [review]
LGTM feel free to merge.

**Comment by LaVLaS** [comment]
I'll follow up and merge this as part of the issue addressed in #110

**Pull request merged**
