### PR TITLE
RHOAIENG-4549 Update the kserve-model-downloader to version v0.11.1.3

### PR DESCRIPTION
**Pull request by jackdelahunt**
## Description
This update may be required to support self signed certificate support for S3 servers

## How Has This Been Tested?
- Use the e2e test provided in the repo
- Run 
```bash
make AWS_SECRET_ACCESS_KEY=... AWS_ACCESS_KEY_ID=... S3_REGION=... S3_ENDPOINT=... IMAGE_REGISTRY_USERNAME=...  IMAGE_REGISTRY_PASSWORD=... S3_BUCKET=... NAMESPACE=... TARGET_IMAGE_TAGS_JSON=... go-test-setup
```

- And then run 
```bash
make AWS_SECRET_ACCESS_KEY=... AWS_ACCESS_KEY_ID=... S3_REGION=... S3_ENDPOINT=... IMAGE_REGISTRY_USERNAME=...  IMAGE_REGISTRY_PASSWORD=...  S3_BUCKET=... NAMESPACE=... TARGET_IMAGE_TAGS_JSON=... go-test
```

## Merge criteria:

- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Review by MarianMacik — APPROVED** [review]
/lgtm

Will wait for Landon to have the final call.

**Review by grdryn — APPROVED** [review]
/lgtm

**Comment by LaVLaS** [comment]
/approved

Preserves existing functionality while providing the features to include a self-signed certificate

**Pull request merged**
